---
title: "Oxoline meta-analysis"
author: "Sasha Mikheyev"
date: "3/12/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(library(tidyverse))
library(googlesheets4)
library(meta)
library(gridExtra)
library(pwr) 
# needed for RStudio server:
# sheets_auth(use_oob = T)
```

Reading Oxoline data from Google Sheets

#https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R


```{r readSheet}
oxoline <- read_sheet("https://docs.google.com/spreadsheets/d/1BwobMKFcXofwaPSTj-JmEY-cGfh61SGZfJfjs4EnnG0") %>% filter(!is.na(`prop control`)) %>% transmute(`n control` = round(`n control`), `n treatment` = round(`n treatment`), `n affected treatment` =  round(`n affected treatment`), `n affected control` = round(`n affected control`), paper = Paper, `double-blind` = `double-blind`, published = published )
```
```{r}
oxoline.bin <- metabin(`n affected treatment`, `n treatment`, `n affected control`, `n control`, data = oxoline, 
                       studlab = paste(paper), comb.fixed = FALSE, comb.random = TRUE, method.tau = "SJ", hakn = TRUE,  
                       prediction = TRUE, incr = 0.1, measure ="RR")
summary(oxoline.bin)


# no Bogdanova
oxoline.bin.noBogdanova <- metabin(`n affected treatment`, `n treatment`, `n affected control`, `n control`, 
                data = oxoline %>% filter(published == "published"), 
                studlab = paste(paper), comb.fixed = FALSE, 
                comb.random = TRUE, method.tau = "SJ", hakn = TRUE,  
                       prediction = TRUE, incr = 0.1, measure ="RR")

summary(oxoline.bin.noBogdanova)

labbe.metabin(x = oxoline.bin, bg = "blue", studlab = TRUE, col.random = "red")

forest(oxoline.bin, digits.sd = 2)

oxoline.forest <- with(oxoline.bin,
     tibble(RR = exp(TE), 
           lower = exp(lower), upper = exp(upper),
           study = studlab, `study size` = n.e + n.c, published = oxoline$published))

oxoline.forest$study <- factor(oxoline.forest$study, levels = oxoline.forest$study[c(3,4,2,1)])

  p1 <- oxoline.forest %>% ggplot(aes(y = study, x = RR, xmin = lower, xmax = upper )) + 
           geom_point(aes(size = `study size`, color = published)) + geom_pointrange(aes(color = published))  + geom_vline(xintercept = 1, color = "red") + theme_minimal() + xlim(c(0, 1.3)) + xlab("") + scale_color_manual(values = c("black", "grey")) + guides(color = F, size = F) + scale_y_discrete("", labels = expression("Bogdanova, unpublished", paste("Shablovskaya ", italic("et al."), " (1972)"), paste("Zlydnikov ", italic("et al."), " (1970)"), paste("Aksenov ",italic("et al"), " (1970)"))) +  geom_segment(aes(x=exp(oxoline.bin.noBogdanova$lower.random),y=0,xend=exp(oxoline.bin.noBogdanova$upper.random),yend=0), color="grey", size = 2) + geom_segment(aes(x=exp(oxoline.bin$lower.random),y=0,xend=exp(oxoline.bin$upper.random),yend=0), color = "black", size = 2) + ggtitle("Relative risk with oxoline prophylaxis") 

```

```{r forest plot}
tab_base <- ggplot(oxoline.forest, aes(y=study)) +
    ylab(NULL) + xlab("  ") + 
    theme(plot.title = element_text(hjust = 0.5, size=12), ## centering title on text
        axis.text.x=element_text(color="white"), ## need text to be printed so it stays aligned with figure but white so it's invisible
        axis.line=element_blank(),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.y=element_blank(),legend.position="none",
        panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),plot.background=element_blank()) 

tab1 <- tab_base + 
    geom_text(aes(x=1, label=`study size`)) + 
    ggtitle("Study size") +  geom_segment(aes(x=1,y=0,xend=1,yend=0), color = "white", size = 2)

lay <-  matrix(c(1,1,1,1,1,1,2), nrow=1)
g <- grid.arrange(p1, tab1, nrow = 1, layout_matrix = lay)
ggsave(height=2, width = 6, file = "plots/forest.pdf", g)
```

## Power analysis

```{r}
h <- ES.h(0.214,	0.169)
pwr.2p.test(h, (119 + 366)/2, sig.level = 0.05, power = NULL)
```